# Runner informaiton:
# Standard F8s_v2 (8 vcpus, 16 GiB memory)
# Intel Xeon® Platinum 8168 (SkyLake)

name: asv-benchmarks

env:
  OUTPUT_PATH: ${{ github.workspace }}
  RESOURCE_GROUP: devito-regression
  VM_NAME: asv-runner-00

on:
  # Trigger the workflow on push to the master branch
  push:
    branches:
      - master

jobs:
  # Boot the self-hosted runner and start runner app
  start-runner:
    name: start-runner
    runs-on: ubuntu-latest

    steps:
    - name: checkout repo
      uses: actions/checkout@v1

    - name: start VM
      env:
        SP_APPID: ${{ secrets.SERVICE_PRINCIPAL_APPID }}
        SP_SECRET: ${{ secrets.SERVICE_PRINCIPAL_SECRET }}
        TENANT_ID: ${{ secrets.SERVICE_PRINCIPAL_TENANTID }}
        SUB_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      run: >
        pwsh -command "& '${{ env.OUTPUT_PATH }}\.github\azure\startVM.ps1'"
        -servicePrincipal $SP_APPID
        -servicePrincipalSecret $SP_SECRET
        -servicePrincipalTenantId $TENANT_ID
        -azureSubscriptionName $SUB_ID
        -resourceGroupName $RESOURCE_GROUP
        -vmName $VM_NAME

    - name: set host
      run: echo ::set-output name=action_host::$(az vm show -d -g $RESOURCE_GROUP -n $VM_NAME --query publicIps -o tsv)
      id: host

    - name: start actions runner app
      uses: fifsky/ssh-action@master
      with:
        command: |
          #!/bin/bash
          nohup actions-runner/run.sh >/dev/null 2>&1 &
        host: ${{ steps.host.outputs.action_host }}
        user: ${{ secrets.CI_GPU_VM_ADMIN_LOGIN }}
        pass: ${{ secrets.CI_GPU_VM_ADMIN_PASSWORD }}
        args: "-tt"

  # Run the asv benchmarks on the self-hosted runner
  benchmarks:
    name: benchmarks
    needs: start-runner
    runs-on: [self-hosted, asv]

    env:
      DEVITO_ARCH: "gcc-9"
      DEVITO_LANGUAGE: "openmp"
      DEVITO_BENCHMARKS: "1"
      DEVITO_LOGGING: "PERF"
      OMP_NUM_THREADS: "8"
      CC: "gcc-9"
      CXX: "g++-9"

    steps:
    - name: Checkout devito
      uses: actions/checkout@v1

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -e .
        pip install asv --upgrade

    - name: Setup asv
      run: |
        bash benchmarks/regression/merge_history.sh
        cp merge_history.txt benchmarks/regression/
        asv machine --config benchmarks/regression/asv.conf.json --yes

    - name: Run benchmarks
      run: |
        asv run -v --show-stderr --config benchmarks/regression/asv.conf.json HASHFILE:merge_history.txt --cpu-affinity 0-7

    - name: Create results (html)
      run: |
        asv publish --config benchmarks/regression/asv.conf.json

    - name: Deploy results to devitocodes/devito-performance/gh-pages
      uses: peaceiris/actions-gh-pages@v2.5.0
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        EXTERNAL_REPOSITORY: devitocodes/devito-performance
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./benchmarks/regression/.asv/html

  # Stop the runner
  stop-runner:
    name: stop-runner
    needs: benchmarks
    runs-on: ubuntu-latest

    steps:
    - name: checkout repo
      uses: actions/checkout@v1

    - name: stop VM
      env:
        SP_APPID: ${{ secrets.SERVICE_PRINCIPAL_APPID }}
        SP_SECRET: ${{ secrets.SERVICE_PRINCIPAL_SECRET }}
        TENANT_ID: ${{ secrets.SERVICE_PRINCIPAL_TENANTID }}
        SUB_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      run: >
        pwsh -command "& '${{ env.OUTPUT_PATH }}\.github\azure\stopVM.ps1'"
        -servicePrincipal $SP_APPID
        -servicePrincipalSecret $SP_SECRET
        -servicePrincipalTenantId $TENANT_ID
        -azureSubscriptionName $SUB_ID
        -resourceGroupName $RESOURCE_GROUP
        -vmName $VM_NAME
